apiVersion: apps/v1
kind: Deployment
metadata:
  name: sat853-deployment
spec:
  selector:
    matchLabels:
      app: sat853-devops-project
  replicas: 2 # tells deployment to run 2 pods matching the template
 
  template:
    metadata:
      labels:
        app: sat853-devops-project
    spec:
      containers:
      - name: sat853-devops-project
        image: sat853/simple-devops-image
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
