---
- hosts: all
  #  become: true

  tasks:
  - name: build docker image
    command: docker build  -t simple-devops-image .
    args:
      chdir: /opt/docker

  - name: change tag
    command: docker tag simple-devops-image sat853/simple-devops-image:latest
    
  - name: push image to docker hub
    command: docker push sat853/simple-devops-image:latest

  - name: remove docker image
    command: docker rmi simple-devops-image sat853/simple-devops-image:latest
    ignore_errors: yes   
